http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    paths: '/users/*'
  posts:
    paths: '/posts/*'
  feed:
    paths: '/feed/*'
serviceEndpoints:
  userService:
    url: 'http://localhost:3001'
  postService:
    url: 'http://localhost:3002'
  feedService:
    url: 'http://localhost:3003'
policies:
  - proxy
pipelines:
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
          action:
            serviceEndpoint: userService
            changeOrigin: true
            stripPath: true
  posts:
    apiEndpoints:
      - posts
    policies:
      - proxy:
          action:
            serviceEndpoint: postService
            changeOrigin: true
            stripPath: true
  feed:
    apiEndpoints:
      - feed
    policies:
      - proxy:
          action:
            serviceEndpoint: feedService
            changeOrigin: true
            stripPath: true
