# system.config.yml

# plugins to load
plugins: {}

# gateway config
db:
  redis:
    emulate: true
    # Setting emulate to true will use an in-memory db, no Redis needed
    # host: localhost
    # port: 6379
    namespace: EG

crypto:
  cipherKey: your-super-secret-jwt-key-change-in-production
  algorithm: aes256
  saltRounds: 10
