name: Blog Microservices Simple Build

on:
  push:
    branches: [ main, master, develop, feature/*, bugfix/*, hotfix/* ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm install

      - name: Build user-service
        run: cd user-service && npm ci && npm run build

      - name: Build post-service
        run: cd post-service && npm ci && npm run build

      - name: Build feed-service
        run: cd feed-service && npm ci && npm run build

      - name: Build api-gateway
        run: cd api-gateway && npm ci

      - name: Build frontend
        run: cd Frontend && npm ci && npm run build

      - name: Run tests
        run: |
          cd user-service && npm test || echo "No tests found, continuing..."
          cd ../post-service && npm test || echo "No tests found, continuing..."
          cd ../feed-service && npm test || echo "No tests found, continuing..."
          cd ../api-gateway && npm test || echo "No tests found, continuing..."

  docker-build:
    needs: build-and-test
    if: success() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, post-service, feed-service, api-gateway, Frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
